version: 0.1
log:
    fields:
        service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /export/registry-fs
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        certificate: /export/ca.crt
        key: /export/ca.key
auth:
  htpasswd:
    realm: basic-realm
    path: /export/htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
